### ISSUE TITLE
installation does not work on debian 9

### ISSUE THREAD

**Issue by payback007** [vatesfr/xo#142]
index generated src/xapi/mixins/index.js
index generated src/api/index.js
index generated src/xo-mixins/index.js
Killed
* vhd-lib:prebuild − Error: 137
* vhd-lib:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* value-matcher:prebuild − Error: 137
* value-matcher:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* complex-matcher:prebuild − Error: 137
* complex-matcher:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-transport-nagios:prebuild − Error: 137
* xo-server-transport-nagios:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
index generated src/commands/index.jsKilled
* xo-server-auth-saml:prebuild − Error: 137
* xo-server-auth-saml:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/

* vhd-cli:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-vmdk-to-vhd:prebuild − Error: 137
* xo-vmdk-to-vhd:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-transport-xmpp:prebuild − Error: 137
* xo-server-transport-xmpp:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-common:prebuild − Error: 137
* xo-common:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-transport-slack:prebuild − Error: 137
* xo-server-transport-slack:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* @xen-orchestra/fs:prebuild − Error: 137
* @xen-orchestra/fs:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-backup-reports:prebuild − Error: 137
* xo-server-backup-reports:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-web:prebuild − Error: 137
* xo-web:build − NODE_ENV=production gulp build
Killed
* xo-server-perf-alert:prebuild − Error: 137
* xo-server-perf-alert:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/

**Comment by payback007** [comment]
yes I followed the instructions, in prior starting I installed a clean/fresh Debian 9.4 system. It seems something is not working during yarn build. I also installed it more than once but now it's not working...

output after yarn build:

yarn run v1.7.0
$ scripts/run-script --parallel build
* complex-matcher:prebuild − yarn run clean
* value-matcher:prebuild − yarn run clean
* vhd-cli:prebuild − rimraf dist/ && index-modules --cjs-lazy src/commands
* vhd-lib:prebuild − yarn run clean
* xen-api:prebuild − rimraf dist/
* xo-cli:prebuild − rimraf dist/
* xo-collection:prebuild − rimraf dist/
* xo-common:prebuild − yarn run clean
* xo-lib:prebuild − rimraf dist/
* xo-remote-parser:prebuild − rimraf dist/
* xo-server:prebuild − index-modules src/api src/xapi/mixins src/xo-mixins && yarn run clean
* xo-server-auth-google:prebuild − rimraf dist/
* xo-server-auth-ldap:prebuild − rimraf dist/
* xo-server-auth-saml:prebuild − yarn run clean
* xo-server-backup-reports:prebuild − yarn run clean
* xo-server-cloud:prebuild − yarn run clean
* xo-server-perf-alert:prebuild − yarn run clean
* xo-server-transport-email:prebuild − rimraf dist/
* xo-server-transport-nagios:prebuild − yarn run clean
* xo-server-transport-slack:prebuild − yarn run clean
* xo-server-transport-xmpp:prebuild − yarn run clean
* xo-server-usage-report:prebuild − yarn run clean
* xo-vmdk-to-vhd:prebuild − yarn run clean
* xo-web:prebuild − yarn run clean && index-modules --auto src
* @xen-orchestra/cron:prebuild − yarn run clean
* @xen-orchestra/fs:prebuild − yarn run clean
* xo-acl-resolver:build − babel --source-maps --out-dir=dist/ src/
* xo-server-auth-github:build − NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-server-load-balancer:build − NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-lib:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xen-api:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-cli:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-remote-parser:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-server-auth-google:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-server-auth-ldap:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-collection:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
* xo-server-transport-email:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Getötet
xenorchestra@XenOrchestra:~/xen-orchestra$ index generated src/api/index.js
index generated src/xapi/mixins/index.js
index generated src/xo-mixins/index.js
Killed
* vhd-lib:prebuild − Error: 137
* vhd-lib:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-cloud:prebuild − Error: 137
* xo-server-cloud:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* complex-matcher:prebuild − Error: 137
* complex-matcher:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-perf-alert:prebuild − Error: 137
* xo-server-perf-alert:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-backup-reports:prebuild − Error: 137
* xo-server-backup-reports:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* @xen-orchestra/cron:prebuild − Error: 137
* @xen-orchestra/cron:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-web:prebuild − Error: 137
* xo-web:build − NODE_ENV=production gulp build
Killed
* value-matcher:prebuild − Error: 137
* value-matcher:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
index generated src/commands/index.js
* vhd-cli:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-transport-nagios:prebuild − Error: 137
* xo-server-transport-nagios:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-usage-report:prebuild − Error: 137
* xo-server-usage-report:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-common:prebuild − Error: 137
* xo-common:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* @xen-orchestra/fs:prebuild − Error: 137
* @xen-orchestra/fs:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-transport-slack:prebuild − Error: 137
* xo-server-transport-slack:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-transport-xmpp:prebuild − Error: 137
* xo-server-transport-xmpp:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-vmdk-to-vhd:prebuild − Error: 137
* xo-vmdk-to-vhd:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server-auth-saml:prebuild − Error: 137
* xo-server-auth-saml:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
* xo-server:prebuild − Error: 137
* xo-server:build − cross-env NODE_ENV=production babel --source-maps --out-dir=dist/ src/
Killed
@babel/preset-env: `DEBUG` option
* xo-acl-resolver:build − Error: 137

Using targets:
{
  "node": "4"
}

Using modules transform: commonjs

Using plugins:
  transform-function-name { "node":"4" }
  transform-arrow-functions { "node":"4" }
  transform-classes { "node":"4" }
  transform-object-super { "node":"4" }
  transform-for-of { "node":"4" }
  transform-sticky-regex { "node":"4" }
  transform-unicode-regex { "node":"4" }
  transform-spread { "node":"4" }
  transform-parameters { "node":"4" }
  transform-destructuring { "node":"4" }
  transform-block-scoping { "node":"4" }
  transform-new-target { "node":"4" }
  transform-regenerator { "node":"4" }
  transform-exponentiation-operator { "node":"4" }
  transform-async-to-generator { "node":"4" }
  proposal-async-generator-functions { "node":"4" }
  proposal-object-rest-spread { "node":"4" }
  proposal-unicode-property-regex { "node":"4" }
  transform-dotall-regex { "node":"4" }
  proposal-optional-catch-binding { "node":"4" }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
Killed
* xo-server-auth-github:build − Error: 137
@babel/preset-env: `DEBUG` option

Using targets:
{
  "chrome": "65",
  "firefox": "59",
  "ie": "11",
  "ios": "11",
  "node": "6"
}

Using modules transform: commonjs

Using plugins:
  transform-template-literals { "ie":"11" }
  transform-literals { "ie":"11" }
  transform-function-name { "ie":"11", "node":"6" }
  transform-arrow-functions { "ie":"11" }
  transform-classes { "ie":"11" }
  transform-object-super { "ie":"11" }
  transform-shorthand-properties { "ie":"11" }
  transform-duplicate-keys { "ie":"11" }
  transform-computed-properties { "ie":"11" }
  transform-for-of { "ie":"11", "node":"6" }
  transform-sticky-regex { "ie":"11" }
  transform-unicode-regex { "ie":"11" }
  transform-spread { "ie":"11" }
 transform-parameters { "ie":"11" }
  transform-destructuring { "ie":"11", "node":"6" }
  transform-block-scoping { "ie":"11" }
  transform-new-target { "ie":"11" }
  transform-regenerator { "ie":"11" }
  transform-exponentiation-operator { "ie":"11", "node":"6" }
  transform-async-to-generator { "ie":"11", "node":"6" }
  proposal-async-generator-functions { "ie":"11", "ios":"11", "node":"6" }
  proposal-object-rest-spread { "ie":"11", "ios":"11", "node":"6" }
  proposal-unicode-property-regex { "firefox":"59", "ie":"11", "ios":"11", "node":"6" }
  transform-dotall-regex { "firefox":"59", "ie":"11", "ios":"11", "node":"6" }
  proposal-optional-catch-binding { "chrome":"65", "ie":"11", "ios":"11", "node":"6" }

Using polyfills: No polyfills were added, since the `useBuiltIns` option was not set.
* xen-api:build − Error: 1

**Comment by olivierlambert** [comment]
Hi!

1. This is not the good repo to create issue, please read the CONTRIBUTING section of our doc :)
2. For source install issues it's better to ask on the forum in general.  Because the dev team works everyday with the sources, it's likely a problem on your side, so adding issues on the GH repo relative to your environment will increase our load on bug triage that's not directly related to XO issues

In your case, I suppose you don't have enough RAM  when you build it.
