### ISSUE TITLE
Wrong server credentials fail silently

### ISSUE THREAD

**Issue by mkzero** [vatesfr/xo#16]
When adding a server with credentials that don't work the GUI should report an error and should also not store the entry.

Possible wrong credentials could be:

* Host can not be resolved
* Host down
* Username wrong
* Password wrong

If one of those things come up, the UI should tell the user what is wrong with a meaningful error message instead of failing silently and adding the broken server to the server list.

**Comment by olivierlambert** [comment]
https://github.com/vatesfr/xo-web/issues/234

Done here
