### ISSUE TITLE
Connecting the xen tools image makes the VM unbootable

### ISSUE THREAD

**Issue by Mc128k** [vatesfr/xo#25]
I connected the image with XO and installed the tools, then rebooted the VM. 
After that it wasn't able to boot properly, and the image couldn't be ejected with the web UI, I had to disconnect it from the xen terminal.

You can reproduce the problem by:
- connecting the xen tools image to a vm
- reboot the vm
- it shouldn't be able to boot or eject the image

I hope it's reproducible in your installation

**Comment by olivierlambert** [comment]
Fixed by https://github.com/vatesfr/xo-web/issues/251
