### ISSUE TITLE
xo-scheduler

### ISSUE THREAD

**Issue by julien-f** [vatesfr/xo#26]
[XO-Server](https://github.com/vatesfr/xo-server) plugin to plan jobs.

A job:
- is a list of XO API calls;
- belongs to a user;
- runs at a specific date or at regular dates.

Dev resources:
- https://github.com/rschmukler/agenda

TODO:
- [ ] [Create a plugin architecture in XO-Server](vatesfr/xo-server#37)
- [ ] Specify xo-scheduler
  - [ ] Job behavior
  - [ ] API

**Comment by olivierlambert** [comment]
Already done since 4.1 or 4.2
