### ISSUE TITLE
when creating a new user, have better password creation

### ISSUE THREAD

**Issue by jstreit15** [vatesfr/xo#31]
When creating a new user, could we please either have an option to unmask the password when creating it or prompt for a second time around so that way we can verify that we didn't fat finger it :)

**Comment by julien-f** [comment]
Good idea!

We plan to redesign the users management page very soon while implementing the ACLs, I'll keep your idea in mind.

**Comment by julien-f** [comment]
Issue moved to vatesfr/xo-web#396.
