### ISSUE TITLE
suspend/resume planned?

### ISSUE THREAD

**Issue by uweschaefer** [vatesfr/xo#34]
Am i right to assume that suspend/resume is currently unsupported in XO?
if so, is it planned to be added some day?

**Comment by olivierlambert** [comment]
Hi!

Indeed, it's not supported right now, but not a big deal to implement. I'll probably do it next week. Stay tuned!

**Comment by olivierlambert** [comment]
Done!

Pushed in `next-release` branch of `xo-server` and `xo-web` (see https://github.com/vatesfr/xo-web/issues/186)

Will be merged for the 3.6.1 (or 3.7 depending of the release size)
