### ISSUE TITLE
CPU Usage Summary not right

### ISSUE THREAD

**Issue by sjkeerthi** [vatesfr/xo#35]
Hi

After I added my Xenserver 6.2 host after a few minitues I could see my xen11 and xen12 added where both are same cluster group.

But where HP Blade Server (80x Intel(R) Xeon(R) CPU E7- 4870 @ 2.40GHz) After the VM created I could see the stats are little odd.

vCPUs/CPU usage:
88/80

RAM used:
40%

Running VMs:
38

How Vcpu will be 88

It will be great that if we have a static list where can show Total CPU and allocated CPU free CPU and the same way Memory and Storage will be good.

So that by see this we can know still how much resources are avaliable and can allocate.

And also it will be great if you could collect the RRD statics of the usage of total usage of Xenserver Interface / CPU / Memory

**Comment by olivierlambert** [comment]
Hi @sjkeerthi !

Thanks for your feedback!

* good idea for the CPU list usage, I was thinking about it, but we need a way to display it properly: indeed, you can have CPU over commit (unlike memory and storage)
* we got a problem on global statistics, it's already reported [here](https://github.com/vatesfr/xo-web/issues/51)
* RRD and stats are already planned in the [roadmap](https://github.com/vatesfr/xo/blob/master/roadmap.md), you just have to wait ^^

**Comment by olivierlambert** [comment]
Closing it (answered by the 4.0 release coming)
