### ISSUE TITLE
Error while creating a new VM

### ISSUE THREAD

**Issue by Mc128k** [vatesfr/xo#36]
Hi
I wanted to wait before submitting this bug, but even after the latest update the issue still persists.

Xen Orchestra is unable to create a new VM in any way. Since the first time I installed it, I was never able to do it properly without using XenCenter.

I have a pool with just one server (latest XenServer), and I try to create a VM from the server dropdown menu (otherwise I cannot select internal disks). Unfortunately when saving an error message is displayed, and just a template is created (I believe in the wrong place).

![screenshot 2015-02-17 00 35 47](https://cloud.githubusercontent.com/assets/3678359/6220996/7965414c-b63d-11e4-9b01-99190c507137.png)

As you can see at the bottom of the screenshot, two templates are created before failing.

I have no idea on where to look for logs. The problem is always reproducible though.

**Comment by olivierlambert** [comment]
Hi!

Indeed, that's not normal, it works for a bunch of people!

If you are using XOA, check the server log in `/var/log/syslog` right when you create the VM, it should displays the error cause.

**Comment by Mc128k** [comment]
I tried some different settings, and now it worked! I missed the network part. BUT there are no logs, the error message doesn't explain what is wrong and a garbage VM is still created if something goes wrong. This has to be fixed I think.

**Comment by olivierlambert** [comment]
It's already reported @Mc128k, see https://github.com/vatesfr/xo-web/issues/76 and https://github.com/vatesfr/xo-server/issues/25

**Comment by Mc128k** [comment]
I totally missed the second one, I'm sorry. This looks like a duplicate then, marking as closed. Thanks a lot : )

**Comment by olivierlambert** [comment]
No worries, that's why I'm here: issue triage ;)
