### ISSUE TITLE
Cant login to console xoa3.6

### ISSUE THREAD

**Issue by wingZero21** [vatesfr/xo#39]
Hi,

I have tried both root/root root/xoa but I cant login to the console.

Any ideas why this might be occuring?

**Comment by olivierlambert** [comment]
Hi,

What do you mean login by the console? Using SSH? or using the console view of XOA to have the console and log in?

**Comment by wingZero21** [comment]
Resolved it looks like something was setting a different pass, got it from the vm settings.
