### ISSUE TITLE
Query on xva install via xencentre

### ISSUE THREAD

**Issue by wingZero21** [vatesfr/xo#40]
Hi,

I have imported the XVA file via xencenter and the vm has booted.

Logging in though I cant see any XO services that are running or to restart? Is there anything else you need to do once the VM has loaded in xencentre that I am missing.

**Comment by olivierlambert** [comment]
XO is started automatically, through *systemd*. The [official documentation](https://github.com/vatesfr/xo/blob/master/doc/installation/xoa_installation.md#restart-xoa) explain how to restart the service if needed.

You just need to go your web browser on the XOA given IP (DHCP) and it works.

**Comment by wingZero21** [comment]
Hi,

There is no systemd service on there currently. 

It just says systemctl not found. The file I got was called xoa_3.6_basic.xva

**Comment by olivierlambert** [comment]
What? Are you sure you are using the right VM? Are you logged as *root*?

**Comment by wingZero21** [comment]
Hi,

Yeah I am logged in on XenCentre via the console

**Comment by olivierlambert** [comment]
Can you paste the result of a `ls -l` just after you are logged? With the bash prompt, e.g:
```bash
# ls -l
total 8
drwxr-xr-x 6 root root 4096 Jan 18 20:25 xo-server
drwxr-xr-x 6 root root 4096 Jan 18 20:26 xo-web
```

**Comment by olivierlambert** [comment]
https://github.com/vatesfr/xo-web/issues/234

Done

**Comment by olivierlambert** [comment]
Any feedback with the 3.8 @wingZero21 ?
