### ISSUE TITLE
IO Disk / Network graph

### ISSUE THREAD

**Issue by sjkeerthi** [vatesfr/xo#44]
Hi 

It will be great that if you could add disk & network io graphi will help to see the performance of the disk.

**Comment by olivierlambert** [comment]
Probably, but we need to find a way to display it without overloading the existing charts.

**Comment by olivierlambert** [comment]
After some investigations:

* VBD IOPS are always at 0, even if read/write speeds are > 0. Seems a XenServer problem.
* There no such thing as VIF IOPS: tx/rx in bytes, or also tx/rx errors. That's all.

Until we found why XenServer didn't return any IOPS for VBDs, closing this issue.
