### ISSUE TITLE
ACL need only viewable

### ISSUE THREAD

**Issue by sjkeerthi** [vatesfr/xo#45]
Hi 

I would like to bring up new idea about the acls. There should be acls only to view the VM and storage rather that acls should not have any action buttons to be disable.

I would like to give only view access to the orch

**Comment by julien-f** [comment]
We are currently working on a new implementation of the ACLs (vatesfr/xo-web#209) which should provide the flexibility you need.

**Comment by sjkeerthi** [comment]
While tested the latest build of xo-web@3.8.1 I created the user with permission User I choose an object vm node. But this users could able to proceed all the actions.

Still I could not see any ACLs just users only able to view not to do any action item. He should have only the VM console

**Comment by olivierlambert** [comment]
As explained before, it's currently in development.
