### ISSUE TITLE
ACLs Viewable is didn't work

### ISSUE THREAD

**Issue by sjkeerthi** [vatesfr/xo#47]
With reference issue https://github.com/vatesfr/xo/issues/45

While tested the latest build of xo-web@3.8.1. I created the user with permission User I choose an object vm node. But this users could able to proceed all the actions.

Still I could not see any ACLs just users only able to view not to do any action item. He should have only the VM console rather than reboot / stop VM /.

Even created users could not able to view the graphic report.

**Comment by olivierlambert** [comment]
As explained, it's currently in development. So that's rather normal you can't find it yet. Please read this issue for more: https://github.com/vatesfr/xo-web/issues/209
