### ISSUE TITLE
npm start failure Debian 7.8 

### ISSUE THREAD

**Issue by evook** [vatesfr/xo#49]
Hi, I tried to install XO-Server and XO-Web on a fresh debian 7.8 VM in Hyper-V. I can't figure out where it fails. The 'dist' directory exists, and I modified the path regarding the documentation. Already met this error? Would be nice to receive some help on this.

 # List of files/directories which will be served.
  mounts:
    '/': '/opt/xo-web/dist/'

root@xoa:/opt/xo-server# npm start

> xo-server@3.9.0 start /opt/xo-server
> node bin/xo-server

Error: Cannot find module './dist'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/xo-server/index.js:14:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/xo-server/bin/xo-server:7:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! xo-server@3.9.0 start: `node bin/xo-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xo-server@3.9.0 start script 'node bin/xo-server'.
npm ERR! This is most likely a problem with the xo-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/xo-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls xo-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/xo-server/npm-debug.log
root@xoa:/opt/xo-server# cat /opt/xo-server/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart xo-server@3.9.0
6 info start xo-server@3.9.0
7 verbose unsafe-perm in lifecycle true
8 info xo-server@3.9.0 Failed to exec start script
9 verbose stack Error: xo-server@3.9.0 start: `node bin/xo-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid xo-server@3.9.0
11 verbose cwd /opt/xo-server
12 error Linux 3.2.0-4-amd64
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error xo-server@3.9.0 start: `node bin/xo-server`
17 error Exit status 1
18 error Failed at the xo-server@3.9.0 start script 'node bin/xo-server'.
18 error This is most likely a problem with the xo-server package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node bin/xo-server
18 error You can get their info via:
18 error     npm owner ls xo-server
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by olivierlambert** [comment]
*XOA* is the virtual Appliance, I think you talk about *XO* installed from the sources?

We are in the middle of a release (3.9) and it should be finished tomorrow. Until then and to avoid too much trouble, you can stick to the previous release tag -> https://github.com/vatesfr/xo-server/releases/tag/v3.8.0

**Comment by evook** [comment]
Hi, excuse this the grammar, in the initial post. I edited it a bit, to maintain some readability.

I'll try 3.9 tomorrow and start from scratch. Thanks for your response.

**Comment by olivierlambert** [comment]
No problem, stay tuned, you'll have a [blog post](https://xen-orchestra.com/blog) tomorrow on our blog announcing the production ready state of 3.9 :)

**Comment by evook** [comment]
I am sorry to inform you, that the bug still exists.

I'm quite sure I am missing some dependencies there. What are the ideal specs to follow the installation doc?

node@v0.12.2 or node@v0.10.36 ?
Wheezy or Jessie ?

I have tried countless combinations. Manual binary installation, the repo, n script and so on.

**Comment by julien-f** [comment]
@evook When installed from the sources, you need to compile both xo-web and xo-server:

```
> cd xo-server
> npm i && npm run build # Install dependencies & build
> cd ../xo-web
> npm i && npm run build
```

**Comment by evook** [comment]
I will test again the evening. Would you mind to tell me what version of node and debian is preferred?

**Comment by julien-f** [comment]
I am currently using Debian 8 and XO has been tested with bot Node 0.10 and 0.12.

**Comment by evook** [comment]
It's working. Thank you!
