### ISSUE TITLE
Get usage data by user VM

### ISSUE THREAD

**Issue by wolfman2g1** [vatesfr/xo#53]
This is more of a feature request/ question. Is there a programatic way to get usage info? For example in a shared lab environment to be able to limit the amount of hours a user gets per month or for the business minded folks a way to tie into a billing system

**Comment by olivierlambert** [comment]
Hi!

We explained our plans is this blog post: https://xen-orchestra.com/blog/xo-4-x-starts-to-show-up/ (check the 2 lasts paragraphs).

So as we know now the resources thanks to the RRDs fetched for stats, we could do it. That's just a matter of time :)

**Comment by olivierlambert** [comment]
Done since 4.0
