### ISSUE TITLE
VM Add New Disk Error

### ISSUE THREAD

**Issue by arjing** [vatesfr/xo#58]
xo:api Error: vm.attachDisk(...) → XapiError: DEVICE_ALREADY_EXISTS +17ms

**Comment by julien-f** [comment]
I believe this one has already been fixed in the next-release branch.

@olivierlambert ?

**Comment by olivierlambert** [comment]
I'll try to reproduce on `master` and `next-release` to check if it's already fixed.

**Comment by arjing** [comment]
The same issue is also appeared in “Attach Disk“

**Comment by olivierlambert** [comment]
Fixed in 4.3
