### ISSUE TITLE
Host can't reconnected after being restarted,need restart the system

### ISSUE THREAD

**Issue by arjing** [vatesfr/xo#61]

**Comment by julien-f** [comment]
Thank you for all these precious bug reports.
We have very recently started to develop a [test suite](/vatesfr/xo-test) for [xo-server](/vatesfr/xo-server) which will help us to considerably improve the quality of XO.

Anyway, as a work around, you don't have to restart to completely restart XO: go into the servers panel and disconnect then reconnect the faulty server.

**Comment by olivierlambert** [comment]
Closing until creating a dedicated issue about to deal with disconnected server bahavior
