### ISSUE TITLE
memory leaks?

### ISSUE THREAD

**Issue by sisoftrg** [vatesfr/xo#62]
Xen Orchestra's process node (xo-server) constantly increase it's RSS memory, start swapping and finally killed by OOM:
```
[102289.081574] node invoked oom-killer: gfp_mask=0x201da, order=0, oom_adj=0, oom_score_adj=0
...
[102289.090157] Out of memory: Kill process 29119 (node) score 888 or sacrifice child
[102289.090181] Killed process 29119 (node) total-vm:2633736kB, anon-rss:1436564kB, file-rss:0kB
```

Installed as virtual appliance (xoa_free_4.1.xva) under xenserver 6.2 and updated to latest version from web console (can't find actual version numbers in web).

After first kills, memory of VM was increased to 1.5G + 0.3G swap. This helps only to increase delay between OOM kills.
Web used very rarely and only by one user. XO connected to 4 standalone xenserver hosts, running about 30 VMs.

Any way to decrease/debug memory usage?  I'm not very familiar with nodejs.

logs dont' have any errors:
```
# systemctl status xo-server.service
xo-server.service - XO Server
   Loaded: loaded (/etc/systemd/system/xo-server.service; enabled)
   Active: active (running) since Sat 2015-07-11 13:52:13 UTC; 37min ago
 Main PID: 2649 (node)
   CGroup: name=systemd:/system/xo-server.service
           └─2649 node /usr/local/bin/xo-server

Jul 11 14:29:13 xoa xo-server[2649]: Sat, 11 Jul 2015 14:29:13 GMT xo:api acl.getCurrent(...) → object
Jul 11 14:29:20 xoa xo-server[2649]: Sat, 11 Jul 2015 14:29:20 GMT xo:api acl.getCurrent(...)
Jul 11 14:29:20 xoa xo-server[2649]: Sat, 11 Jul 2015 14:29:20 GMT xo:api acl.getCurrent(...) → object
Jul 11 14:29:23 xoa xo-server[2649]: Sat, 11 Jul 2015 14:29:23 GMT xen-api root@[censored]: event.from(...)
Jul 11 14:29:23 xoa xo-server[2649]: Sat, 11 Jul 2015 14:29:23 GMT xen-api root@[censored]: event.from(...)
Jul 11 14:29:24 xoa xo-server[2649]: Sat, 11 Jul 2015 14:29:24 GMT xo:api acl.getCurrent(...)
Jul 11 14:29:24 xoa xo-server[2649]: Sat, 11 Jul 2015 14:29:24 GMT xo:api acl.getCurrent(...) → object
Jul 11 14:29:28 xoa xo-server[2649]: Sat, 11 Jul 2015 14:29:28 GMT xen-api root@[censored]: event.from(...)
Jul 11 14:29:28 xoa xo-server[2649]: Sat, 11 Jul 2015 14:29:28 GMT xen-api root@[censored]: event.from(...)
Jul 11 14:29:28 xoa xo-server[2649]: Sat, 11 Jul 2015 14:29:28 GMT xo:perf blocked for 13ms
```

**Comment by olivierlambert** [comment]
Current version number is in the "About view" (under the title). You should have the 4.2

That's strange, despite this is an appliance, we don't have the exact same behavior on every installation. E.g: in our lab and in another place, we put probes (Munin) for measuring the RAM and process activity. It's up and running since one month, and we didn't notice this problem.

So far, we got 2 people having this problem. We'll try to track this down as far as we could.


Thanks for your feedback!

**Comment by sisoftrg** [comment]
Yes, 4.2.0 installed.
additionally, stats from Zabbix for last week: http://i.imgur.com/BAvcq57.png

I think that memleaks can be dependent on some info from connected Xen servers.

**Comment by olivierlambert** [comment]
Thanks for the figures :)

**Comment by julien-f** [comment]
Last reports (vatesfr/xo-server#88) indicate that these leaks are no longer present using Node 4.

Feel free to reopen this issue if it is not the case.
