### ISSUE TITLE
Documentation for troubleshooting on non-XOA installations

### ISSUE THREAD

**Issue by kmacphee** [vatesfr/xo#64]
I have followed the manual installation instructions pretty much to the letter, making adjustments for the fact I am running CentOS 7 rather than Debian, and have successfully got XO running against my XenServer.

Unfortunately VM and snapshot creation doesn't seem to work and I can't tell where log entries are being sent, so that I can begin to figure out why. All documentation refers to /var/log/syslog but this is specific to the XOA/Debian and doesn't exist on CentOS 7. There are no apparent entries for XO in /var/log/messages or journalctl.

Could troubleshooting documentation for non-XOA installations be improved?

**Comment by olivierlambert** [comment]
Hi!

Well, the hard thing to document manual install is about the various possibilities to execute `xo-server`: could be start with `npm start`, or using `forever`, `systemd`, custom `initd` script, or whatever you can imagine (and it works on any OS, so MacOS and Windows could also have their own stuff to manage that).

So first thing first, how did you started your `xo-server`?

**Comment by kmacphee** [comment]
I can completely appreciate the difficulty. On inspection I had actually started the server using forever, as advised by the installation guide. I managed to find where forever was writing the log messages to and found no record of any errors in my failed VM/snapshot creation attempts.

I have since restarted the server and both appear to be working now...

My apologies, I hadn't realized that forever was putting it wherever it liked.

**Comment by olivierlambert** [comment]
No worries, you were right to open an issue here if you got a problem :)

In order to find error message, you should have to look the log in the same time when you got the error, because the `xo-server` output is verbose. Any error visible in `xo-web` will trigger something in the `xo-server` log.

If it happens again, feel free to ask here for reopening this issue!
