### ISSUE TITLE
node heap size exceeded with many servers

### ISSUE THREAD

**Issue by snatella** [vatesfr/xo#65]
We've noticed an issue with large numbers of XenServer hosts added and the node process running out of memory.

    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
    Aborted (core dumped)

Is the error we end up with.

It works fine around ~100 hosts, which consumes just over 1GB of memory, but when we double that it tries to allocate over (what my research leads to me to believe is) the 1.9GB artificial limit in node (even on 64bit platforms).

**Comment by olivierlambert** [comment]
Hi,

Are you using XO from the sources or from XOA? How much RAM available on the machine running XO? How many VMs?

**Comment by snatella** [comment]
Hello Olivier,

From sources, current master. Host has 8GB and only runs XO and the
required redis server.

I tried adding 210 servers and it failed to start with the given error.

Thanks,

Simon

**Comment by olivierlambert** [comment]
We can't reproduce the issue, probably because of your infrastructure size. And you are probably right about the Node memory limit.

Can you check this: https://github.com/joyent/node/wiki/FAQ#what-is-the-memory-limit-on-a-node-process

Try to push it at 4GB and tell us how it goes.

**Comment by snatella** [comment]
Hello Olivier, 

This appears to have fixed the issue in our setup, and another side issue we were seeing which was a big slowdown when adding more servers, probably by the gc running too frequently.

Thanks,

Simon

**Comment by olivierlambert** [comment]
That's probably because when you add a server, the initial connection sends a lot of information (all data from the server and its objects). After this step, you just get the events.

Can you send a screenshot of the navbar displaying the infrastructure size? (pool/host/VM numbers)

**Comment by snatella** [comment]
![xo-bar](https://cloud.githubusercontent.com/assets/13870273/9388328/9c72fd0e-475c-11e5-9e8d-d91a595902d9.png)

We use local storage so no point in using pools for us.

Hope this helps.

**Comment by olivierlambert** [comment]
wow! Congrats for being our "largest infrastructure known" user of Xen Orchestra \o/

Any other feedback/problem in XO usage for this huge set of VMs?

**Comment by snatella** [comment]
Hello Olivier,

Now we've got the old space at 6GB it appears to be much faster to start,
and there is no hesitation from the back-end.

The browser is a different story though - a single tab in Chromium/Chrome
will use 750M-1.1G easily, along with up to 80% of a core on an i7 4790 at
peak ('idles' around 40%). It does take about 10 seconds for content to
appear too (you're left with the "You need to add servers" screen until it
does). It can make a duplicate tab operation a little risky... And I don't
dare try it in Firefox at all!

I might suggest a loading mechanic that replaces the default "You need to
add servers" screen in the case when you have servers, it's just taking
some time to load.

And as you may expect, it is a little sluggish in operation. I think that
is probably all client side lag. Not sure how much can be done about that.

Thanks,

Simon

**Comment by olivierlambert** [comment]
@snatella :
* we'll redesign completely the interface (for the end of the year) with those issues in mind
* for the server part, Node 4 should be faster and less prone to potential memory leaks. Try it also :)
