### ISSUE TITLE
Manual install instructions error

### ISSUE THREAD

**Issue by petersvei** [vatesfr/xo#68]
Hi, in the install instructions for xo-server is says that this line has to be set on `.xo-server.yaml`

 `mounts: '/': '../xo-web/dist/'`

When I follow the guide there is no `dist` folder, only `app`. When I set that, and I get the correct logon screen.

**Comment by olivierlambert** [comment]
Hi,

`dist` will appear after the build process (done by `npm run build`)

**Comment by olivierlambert** [comment]
Closing but feel free to comment if you still have problems related to the install.

**Comment by petersvei** [comment]
I don't fully understand, in the guide I'm not supposed to run `npm run build` in `xo-web` before this step. Should I?

There is a dist folder in `xo-server`, is it this one?

**Comment by olivierlambert** [comment]
Yes you are supposed to do it, see https://github.com/vatesfr/xo/blob/master/doc/installation/manual_installation.md#xo-web

**Comment by petersvei** [comment]
Ok, I see, I was fooled by the "You can try to start XO-Server to see if it works. You should have something like that" step and started testing the web access a bit too early. 

Thanks for your help.

**Comment by olivierlambert** [comment]
You are welcome :)

**Comment by petersvei** [comment]
Btw, `npm install` in xo-web throws a bunch of errors and warnings, should I care? I'm on Ubuntu 14.04. Sorry for being off topic, should I open another issue? :)

**Comment by petersvei** [comment]
A small suggestion for the guide, when asked to set the ` mounts: '/': '../xo-web/dist/'` maybe a small note that the folder not yet exists is in place since it will only appear after xo-web install which is in a much later step? Even I doubt so, there might be other people out there as stupid as me :)

**Comment by olivierlambert** [comment]
See the [troubleshooting section](https://github.com/vatesfr/xo/blob/master/doc/installation/manual_installation.md#troubleshooting) for any npm problems. If it continues, [the forum](https://xen-orchestra.com/forum/) is a good place to go :)

**Comment by olivierlambert** [comment]
To be fair, the documentation is exact:

* you can try to start `xo-server` to see if the server part works, even without installing `xo-web` (remember, they are 2 different apps)
* then you can start to install `xo-web`, which is **one** of the way to interact with `xo-server`

That explains why the documentation is written like this. But I agree that's not perfect.

**Comment by petersvei** [comment]
About start and test-thing I agree, but I was referring to the step where you are supposed to config the yaml,  mounts: '/': '../xo-web/dist/' . That is not accurate as you say in all cases, so maybe a not that this folder does not exist unless xo-web is built is useful, at least it would have helped me.

**Comment by olivierlambert** [comment]
Done!

**Comment by petersvei** [comment]
Thanks, for this and the npm-related hints, ill try those. :)

Peter

-----Original Message-----
