### ISSUE TITLE
Local SR vdisk

### ISSUE THREAD

**Issue by dff3bc** [vatesfr/xo#70]
It appears, to me, that if a virtual disk resides on an SR that is local to a specific xen hypervisor, you are not able to attach it to a virtual machine.

**Comment by olivierlambert** [comment]
Hi @dff3bc 

I'm not sure to understand. What is the behavior you expected and the current one?

**Comment by dff3bc** [comment]
Ok, let's assume that I have a hypervisor with two local disks installed. Each disk has been added as a local SR in Xen. If I copy a VDI to the second (not xen os) disk, I cannot attach it to a VM because the SR does not appear in the drop down list. 
![screen shot 2015-10-14 at 6 53 12 am](https://cloud.githubusercontent.com/assets/6216184/10482750/5e3f5f00-7240-11e5-959a-21588ccd448d.png)
![screen shot 2015-10-14 at 6 53 40 am](https://cloud.githubusercontent.com/assets/6216184/10482756/65d631a8-7240-11e5-97fc-c0285e42b363.png)

**Comment by olivierlambert** [comment]
Ok got it, thanks for the clarification! I'll check why, indeed that's not a normal behavior.

**Comment by dff3bc** [comment]
Ok, thank you.

**Comment by olivierlambert** [comment]
@dff3bc is it still the case with 4.10?

**Comment by olivierlambert** [comment]
Closing until further news.
