### ISSUE TITLE
Multiple backup processes can spawn for the same job

### ISSUE THREAD

**Issue by stamp** [vatesfr/xo#74]
Hi!

We started using the new awesome DR and Continuous Replication features of XO and have noticed that the scheduler don't check if the job is "In progress" and can therefore spawn a new parallel process for the same job.

The problem for us was that our connection between the data centers was choked so the first backup job was taking more time than usual. The backup job was running and then the scheduler started a new full backup job and this caused the backup jobs to go even slower.. You probably see the bad spiral here :P 

My suggestion is to have at least a optional setting saying "wait for previous job to finish before start" or something like that.

// stamp

**Comment by olivierlambert** [comment]
Hi!

That's strange: the current behavior is to NOT start a job if there is a currently active job. It should be skipped if it's the case (and won't start it until it's finished).

You shouldn't have this issue. Or maybe you are talking about 2 different jobs?

**Comment by niklashuke** [comment]
we've experienced this on all types of backup jobs. we've manually triggered the job before it's set to run, once it hits the scheduled time. it will start a second running of the same job.  see image
![cont-rep](https://cloud.githubusercontent.com/assets/1170955/12538713/1c5a5a26-c2e1-11e5-8183-842da860468e.PNG)

**Comment by olivierlambert** [comment]
Are you on the last version?

**Comment by niklashuke** [comment]
we're on 4.12 upgraded yesterday.

**Comment by olivierlambert** [comment]
Can you try with a job with only one VM in it?

**Comment by olivierlambert** [comment]
How did you upgraded?

**Comment by niklashuke** [comment]
we upgraded with git. We had this issue with 4.11 aswell. 
we'll do a job with one vm and get back to you

Cheers

**Comment by olivierlambert** [comment]
I assume you made a rebuild after pulling the latest stable?

**Comment by niklashuke** [comment]
yes


here's two pictures of a new job(17). 
21:55 First run was manual and did not complete within the 5 minutes until 22:00. 
22:00 the scheduled job was triggered. 

![job_trigg_by_schedpng](https://cloud.githubusercontent.com/assets/1170955/12538931/f7fb1642-c2e6-11e5-8f16-7857b7da4678.PNG)

**Comment by julien-f** [comment]
Hi, a job cannot been started twice by the scheduler, there is no check for now for manual runs.

**Comment by niklashuke** [comment]
Okey, very definitive answer. Now we know and we'll work around it. :)

Thanks for the almost instant answers and an awesome product!

Cheers

**Comment by julien-f** [comment]
You're welcome, feel free to open a new issue if the behavior is a problem for you :)
