### ISSUE TITLE
After Login get directly logged out

### ISSUE THREAD

**Issue by mike59999** [vatesfr/xo#79]
Hello,

im currenty trying to manual install xo-server and xo-web.
I followed exactly the instruction for manul installation and tried it with Debian 7 and Ubuntu 14.
The installtion itself works but when i try to login i see for 1 second the startpage and then get redirected back to the loginpage.
The username and password are correct because when i try as password 1234 instead of admin then i get the correct message that the credentials are wrong.

EDIT: I tried with stable and with next-release.

**Comment by olivierlambert** [comment]
Which browser are you using?

**Comment by mike59999** [comment]
I tried with Firefox 46.0.1, Chrome 51 and Mircosoft Edge on 2 PC to get sure that it's not a problem with caching.

**Comment by olivierlambert** [comment]
Nothing bad here. And in your browser console?

**Comment by mike59999** [comment]
There are 2 Warnings about Password over Plain http but they are for testing not important.
But you are right there are 2 errors that a connection to ws://192.168.200.201/api/ and s://192.168.200.201/api/updater could not be etablished but i don't understand why.

**Comment by olivierlambert** [comment]
Can you try in HTTPS?

**Comment by julien-f** [comment]
@mike59999 If you have a proxy between xo-web and xo-server it may not handle WebSocket properly, using HTTPs circumvent the problem by hiding WebSocket to the proxy.

**Comment by mike59999** [comment]
Crazy with https it's working. There was no proxy or something like that in use. I started xo as root so that it can use Port 80. Thank you very much i never thought that switching to https could solve the Problem.Is there a option where i can donate some money for your help?

**Comment by julien-f** [comment]
No problem :)

Nope, there are currently no ways to make donations apart from [subscribing to XO](https://xen-orchestra.com/#!/pricing), but you can continue to report issues and submit PRs :smile:
