### ISSUE TITLE
Front-end with problem

### ISSUE THREAD

**Issue by lobocode** [vatesfr/xo#83]
When I create a new host on the network front-end fails to hide the network interface data (as shown in the figure below):
![image](https://cloud.githubusercontent.com/assets/1684061/18448260/bf385056-7900-11e6-91d6-fd16bbf3abc2.png)

**Comment by olivierlambert** [comment]
Hi @lobocode please use [this repo](https://github.com/vatesfr/xo-web/issues) for reporting issues as [explained in the doc](https://xen-orchestra.com/docs/contributing.html#bug-reports).

And while creating it there, please use the pre-filled template :)
