### ISSUE TITLE
Add a Virtual Machine Tab to Host Information

### ISSUE THREAD

**Issue by nrolando46** [vatesfr/xo#84]
it would be nice to have a "Virtual Machine Tab" under the Host for easier access. 

![screen shot 2016-10-03 at 10 17 04 am](https://cloud.githubusercontent.com/assets/17577490/19040628/e73fb8c0-8952-11e6-9c3e-bf5557d87f28.png)

**Comment by fufroma** [comment]
Should be in vates/xo-web . Gonna be deleted from here soon :wink:

May be similar to vatesfr/xo-web#1432

**Comment by olivierlambert** [comment]
Thanks for your feedback @nrolando46 

As @fufroma explained, opened issue should be done there: https://github.com/vatesfr/xo-web/issues/new

It's in our contributing guidelines: https://xen-orchestra.com/docs/contributing.html
